# Neural-Network Basic TensorFlow

Import Library

In [1]:
import numpy as np
import tensorflow as tf

Hyperparameters

In [2]:
learning_rate    = 1e-4
input_dimension  = 4
neuron_per_layer = 20
output_dimension = input_dimension

Create the placeholder for the input and output of the NN, (non trainable variable)

In [3]:
INPUT  = tf.placeholder(tf.float32, [None,  input_dimension])
OUTPUT = tf.placeholder(tf.float32, [None, output_dimension])

Create the Weight we are gonna modifiy to improve network accuracy (i'll set them to random value from a normal distribution with std_dev = 0.1 because it's a good stocastic inizialization)

In [4]:
W_i = tf.Variable(tf.truncated_normal([input_dimension,neuron_per_layer], stddev=0.1), dtype=tf.float32)
b_i = tf.Variable(tf.truncated_normal([neuron_per_layer], stddev=0.1), dtype=tf.float32)

W   = tf.Variable(tf.truncated_normal([neuron_per_layer,neuron_per_layer], stddev=0.1), dtype=tf.float32)
B   = tf.Variable(tf.truncated_normal([neuron_per_layer], stddev=0.1), dtype=tf.float32)

W_o = tf.Variable(tf.truncated_normal([neuron_per_layer,output_dimension], stddev=0.1), dtype=tf.float32)
b_o = tf.Variable(tf.truncated_normal([output_dimension], stddev=0.1), dtype=tf.float32)

Actual NN model

In [5]:
a = tf.add(tf.matmul(INPUT,W_i),b_i)
a = tf.nn.sigmoid(a)
a = tf.add(tf.matmul(a,W),B)
a = tf.nn.sigmoid(a)
a = tf.add(tf.matmul(a,W_o),b_o)
output = tf.nn.sigmoid(a)

Define the cost function we are gonna differentiate

In [6]:
cost = tf.reduce_mean(tf.losses.sigmoid_cross_entropy(OUTPUT,logits=output))

Set the optimizer

In [7]:
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

Actually create the computation graph and initilize the variables

In [8]:
sess = tf.InteractiveSession()
tf.global_variables_initializer().run()

### Test the NN

Create random data

In [9]:
dummy_data = np.random.rand(1,input_dimension)

print(dummy_data)

[[ 0.90055322  0.40943323  0.33231894  0.34095264]]


Calculate the output

In [10]:
print(sess.run(output,feed_dict={INPUT:dummy_data}))

[[ 0.51885015  0.491552    0.47235176  0.46274254]]


### Generate Data To Train The NN

How many pair Input,Output are we gonna generate

In [11]:
n_of_pair_of_data = 10000

Generate NOT Pair of array

In [12]:
X = np.random.randint(0,2,(n_of_pair_of_data,input_dimension))
Y = 1 - X

print("X\n%s"%X)
print("Y\n%s"%Y)

X
[[1 0 0 1]
 [1 1 1 0]
 [0 1 1 1]
 ..., 
 [1 0 1 0]
 [1 0 1 0]
 [1 1 0 1]]
Y
[[0 1 1 0]
 [0 0 0 1]
 [1 0 0 0]
 ..., 
 [0 1 0 1]
 [0 1 0 1]
 [0 0 1 0]]


### Train the NN

How many iteration of training we are gonna do

In [13]:
n_of_iteration = 100
batch_size = 10

Train loop and print output every 20 iteration

In [14]:
for i in range(n_of_iteration):
    #train for batches
    for j in range(n_of_pair_of_data//batch_size):
        i1 = batch_size*j
        i2 = batch_size*(j+1)
        sess.run(optimizer,feed_dict={INPUT:X[i1:i2],OUTPUT:Y[i1:i2]})
    
    #print stuff
    if i % 10 == 0:
        print(i)
        j = np.random.randint(0,input_dimension - 1)
        res = sess.run(output,feed_dict={INPUT:X[j].reshape((1,input_dimension))})[0]
        print("result: \t%s"%res)
        #convert to 1 an 0 from probability
        res = np.array(res > 0.5,dtype=np.int)
        print("casted: \t%s"%res)
        print("original\t%s"%Y[j])

0
result: 	[ 0.31442097  0.30756313  0.30055854  0.2953698 ]
casted: 	[0 0 0 0]
original	[1 0 0 0]
10
result: 	[ 0.06017575  0.08183844  0.06820544  0.07080541]
casted: 	[0 0 0 0]
original	[1 0 0 0]
20
result: 	[ 0.09279105  0.11867038  0.11614312  0.08481433]
casted: 	[0 0 0 0]
original	[0 0 0 1]
30
result: 	[ 0.00416189  0.04918669  0.20224065  0.07527158]
casted: 	[0 0 0 0]
original	[0 0 0 1]
40
result: 	[ 0.06182946  0.79773039  0.91894776  0.18142706]
casted: 	[0 1 1 0]
original	[0 1 1 0]
50
result: 	[  5.85816952e-06   3.90582671e-03   2.78815697e-03   9.87225354e-01]
casted: 	[0 0 0 1]
original	[0 0 0 1]
60
result: 	[  1.37719873e-03   9.97793674e-01   9.99497056e-01   4.78220201e-04]
casted: 	[0 1 1 0]
original	[0 1 1 0]
70
result: 	[  1.94223446e-08   1.14442228e-04   4.74210901e-05   9.99866247e-01]
casted: 	[0 0 0 1]
original	[0 0 0 1]
80
result: 	[  2.90364488e-09   1.57282466e-05   1.68735551e-05   5.75285640e-06]
casted: 	[0 0 0 0]
original	[1 0 0 0]
90
result: 	[  3.6016

### Test the NN

In [15]:
X_test = np.random.randint(0,2,(1,input_dimension))
res = sess.run(output,feed_dict={INPUT:X_test})
print(res)
res = np.array(res > 0.5,dtype=np.int)
print(res)
print(X_test)

[[  9.99998927e-01   9.99998212e-01   9.99999046e-01   8.56282213e-07]]
[[1 1 1 0]]
[[0 0 0 1]]
